# Generated by Django 4.2.4 on 2023-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorysafeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
