name: GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to execute the workflow against'
        required: true

jobs:
  your-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
